# Generated by Django 5.0.6 on 2024-07-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='城市名')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(verbose_name='距离')),
                ('cityA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asA', to='transportation.city')),
                ('cityB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asB', to='transportation.city')),
            ],
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='票价')),
                ('mileage', models.IntegerField(verbose_name='里程')),
                ('depart_time', models.DateTimeField(verbose_name='出发时间')),
                ('arrive_time', models.DateTimeField(verbose_name='到达时间')),
                ('time_cost', models.DurationField(blank=True, null=True, verbose_name='耗时')),
                ('departure_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asDeparture', to='transportation.city')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asDestination', to='transportation.city')),
            ],
        ),
    ]
